# This is the standard configuration for deploying a Vite project on Netlify.
[build]
  # This command tells Netlify to run the "build" script from your package.json.
  # It will compile your TypeScript and optimize the app for production.
  command = "npm run build"
  
  # This tells Netlify that the final, public website files will be in a folder named "dist".
  # This is the default output directory for Vite.
  publish = "dist"