# This configuration file instructs Netlify on how to build and deploy your site.
[build]
  # This 'command' runs during the build process on Netlify's servers.
  # It uses a standard tool (sed) to securely find the placeholder text '%%GEMINI_API_KEY%%'
  # in your index.html file and replace it with the actual secret API key
  # you have stored as 'GEMINI_API_KEY' in your Netlify environment variables.
  command = "sed -i 's|%%GEMINI_API_KEY%%|'\"$GEMINI_API_KEY\"'|g' index.html"
  
  # This tells Netlify where to find the site to deploy *after* the command runs.
  # Since your project is not a typical compiled app, the publish directory is the root itself.
  # This line specifically fixes the "Deploy directory 'dist' does not exist" error.
  publish = "."